### ISSUE TITLE
בדיקת המטלה

### ISSUE THREAD

**Issue by michael-lemberger** [PikaTeam/Week8-Homework#1]
עבודה טובה סך הכל, נא להוסיף טסטים והערות. איך בדקתם שהאלגוריתם עובד?

**Comment by neyney10** [comment]
הוספנו טסטים לאלגוריתם בנפרד
וגם הוספנו אתה הערות מפורטות יותר לאלגוריתם במחלקה שלו.

בדקנו תחילה את האלגוריתם על ידי בדיקות אינטגרציה - כלומר, הרצה של המשחק ולא על ידי בדיקות יחידה על מנת לבודד את המחלקה.

כפי שנאמר, עכשיו נוספו גם בדיקות יחידה, נא להסתכל ברידמי המעודכן.

**Comment by neyney10** [comment]
> 
> 
> עבודה טובה סך הכל, נא להוסיף טסטים והערות. איך בדקתם שהאלגוריתם עובד?

הוספנו טסטים לאלגוריתם בנפרד
וגם הוספנו אתה הערות מפורטות יותר לאלגוריתם במחלקה שלו.

בדקנו תחילה את האלגוריתם על ידי בדיקות אינטגרציה - כלומר, הרצה של המשחק ולא על ידי בדיקות יחידה על מנת לבודד את המחלקה.

כפי שנאמר, עכשיו נוספו גם בדיקות יחידה, נא להסתכל ברידמי המעודכן.
